# Generated by Django 3.2.12 on 2022-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-tcreated']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
