# Generated by Django 3.2.12 on 2022-08-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['tcreated']},
        ),
    ]
